service:
  name: ui
  type: ClusterIP
  annotations: {}
  servicePort: 8080
http_port: 8080
container_port: 8080
image:
  repository:  cschreep/helx-search-ui
  pullPolicy: Always
imagePullSecrets: []
# Add any extra environment variables not already defined in the chart.
extraEnv: []
resources:
  limits:
    cpu: 200m
    memory: 320Mi
  requests:
    cpu: 50m
    memory: 64Mi
enabled: true
app_name: ui

api_url: "http://localhost:5551"
node_env: development

appPort: 8080
containerPort: 8080
